from PyQt5 import QtCore, QtGui, QtWidgets, uic

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 582)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.blue = QtWidgets.QWidget(Form)
        self.blue.setMinimumSize(QtCore.QSize(0, 300))
        self.blue.setStyleSheet("QWidget {\n"
                                "    border-radius: 0px 0px 10px 10px;\n"
                                "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #D5E6EF, stop:0.297 #1372A0);\n"
                                "}\n"
                                "")
        self.blue.setObjectName("blue")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.blue)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.blue)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setStyleSheet("    border-radius: 10px; /* Adjust the value to control the roundness */\n"
                                    "    background-color: #ffffff; /* Set the background color */")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)

        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("color: black")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.blue)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        # self.widget_4 = QtWidgets.QWidget(self.widget)
        # self.widget_4.setStyleSheet("background-color: rgb(238, 246, 249);")
        # self.widget_4.setObjectName("widget_4")
        # self.verticalLayout.addWidget(self.widget_4)
        # self.widget_5 = QtWidgets.QWidget(self.widget)
        # self.widget_5.setStyleSheet("background-color: rgb(238, 246, 249);")
        # self.widget_5.setObjectName("widget_5")
        # self.verticalLayout.addWidget(self.widget_5)
        # self.widget_6 = QtWidgets.QWidget(self.widget)
        # self.widget_6.setStyleSheet("background-color: rgb(238, 246, 249);")
        # self.widget_6.setObjectName("widget_6")
        # self.verticalLayout.addWidget(self.widget_6)
        # self.widget_7 = QtWidgets.QWidget(self.widget)
        # self.widget_7.setStyleSheet("background-color: rgb(238, 246, 249);")
        # self.widget_7.setObjectName("widget_7")
        # self.verticalLayout.addWidget(self.widget_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.widget_8)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setStyleSheet("border: 1.5px solid black; border-radius: 5%")
        self.comboBox.setMinimumHeight(30)
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("color: black")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 2)
        self.widget_3 = QtWidgets.QWidget(self.blue)
        self.widget_3.setStyleSheet("    border-radius: 10px; /* Adjust the value to control the roundness */\n"
                                    "    background-color: #ffffff; /* Set the background color */")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("color: black")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.gridLayout_2.addWidget(self.widget_3, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.blue, 1, 0, 1, 1)
        self.black = QtWidgets.QWidget(Form)
        self.black.setMinimumSize(QtCore.QSize(0, 100))
        self.black.setMaximumSize(QtCore.QSize(16777215, 100))
        self.black.setSizeIncrement(QtCore.QSize(0, 0))
        self.black.setStyleSheet("QWidget {\n"
                                 "    border-radius: 10px 10px 0px 0px;\n"
                                 "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0.69), stop:0.01 #000, stop:0.3521 rgba(0, 0, 0, 0.66), stop:0.774 rgba(0, 0, 0, 0.66));\n"
                                 "}\n"
                                 "")
        self.black.setObjectName("black")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.black)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.black)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"app/view/src/logo.png"))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.black)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("color : white")
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_2.raise_()
        self.label.raise_()
        self.gridLayout.addWidget(self.black, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "Отправить"))
        self.pushButton.setText(_translate("Form", "Отправить"))
        self.pushButton.setStyleSheet("border: 1.5px solid black; border-radius: 5%")
        self.pushButton_3.setText(_translate("Form", "Получить"))
        self.label_2.setText(_translate("Form", "IP"))

    def isclicked(self):
        if (self.pushButton_2.click()):
            self.pushButton_2.setStyleSheet("color : red")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
